# Generated by Django 2.2.12 on 2021-11-02 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='card_type',
            field=models.CharField(blank=True, choices=[('mastercard', 'mastercard'), ('visa', 'visa'), ('american_express', 'American Express'), ('discover', 'Discover')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
