# Generated by Django 2.2.12 on 2021-11-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211102_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetail',
            name='action',
        ),
    ]
