# Generated by Django 2.2.12 on 2021-11-02 16:15

from django.db import migrations, models
import payment.validators


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_carddetail_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddetail',
            name='cvv',
            field=models.PositiveIntegerField(default=100, validators=[payment.validators.cvv_validator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_number',
            field=models.CharField(max_length=16, validators=[payment.validators.card_number_validator]),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='card_type',
            field=models.CharField(choices=[('mastercard', 'mastercard'), ('visa', 'visa'), ('american_express', 'American Express'), ('discover', 'Discover')], max_length=30, validators=[payment.validators.card_type_choice_validator]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
